version: '3'
services:
  backend:
    build:
      context: .
    command:  bash -c "python app/manage.py migrate && python app/manage.py collectstatic --noinput && gunicorn --chdir /shegagiveaway/app app.wsgi --workers 3 --timeout 90 -b :8000"
    ports:
      - 8000:8000
    depends_on:
      - postgres
  postgres:
    build: 
      context: ./db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=shega
      - POSTGRES_PASSWORD=mysecurepassword
    volumes:
      - db:/var/lib/postgresql/data
    restart: on-failure
volumes:
  db: 
