version: '3'
services:
 backend:
    build:
      context: .
    command:  bash -c "python app/manage.py migrate && python app/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000

    restart: on-failure